import { indexBy } from "remeda";

export type Character = Readonly<{
	acceptedAnswers: string[];
	kana: string;
	romaji: string;
}>;

export type KanaType = "hiragana" | "katakana";

export const hiragana = [
	{ acceptedAnswers: ["a"], kana: "あ", romaji: "a" },
	{ acceptedAnswers: ["i"], kana: "い", romaji: "i" },
	{ acceptedAnswers: ["u"], kana: "う", romaji: "u" },
	{ acceptedAnswers: ["e"], kana: "え", romaji: "e" },
	{ acceptedAnswers: ["o"], kana: "お", romaji: "o" },
	{ acceptedAnswers: ["ka"], kana: "か", romaji: "ka" },
	{ acceptedAnswers: ["ki"], kana: "き", romaji: "ki" },
	{ acceptedAnswers: ["ku"], kana: "く", romaji: "ku" },
	{ acceptedAnswers: ["ke"], kana: "け", romaji: "ke" },
	{ acceptedAnswers: ["ko"], kana: "こ", romaji: "ko" },
	{ acceptedAnswers: ["sa"], kana: "さ", romaji: "sa" },
	{ acceptedAnswers: ["shi"], kana: "し", romaji: "shi" },
	{ acceptedAnswers: ["su"], kana: "す", romaji: "su" },
	{ acceptedAnswers: ["se"], kana: "せ", romaji: "se" },
	{ acceptedAnswers: ["so"], kana: "そ", romaji: "so" },
	{ acceptedAnswers: ["ta"], kana: "た", romaji: "ta" },
	{ acceptedAnswers: ["chi", "ti"], kana: "ち", romaji: "chi" },
	{ acceptedAnswers: ["tsu"], kana: "つ", romaji: "tsu" },
	{ acceptedAnswers: ["te"], kana: "て", romaji: "te" },
	{ acceptedAnswers: ["to"], kana: "と", romaji: "to" },
	{ acceptedAnswers: ["na"], kana: "な", romaji: "na" },
	{ acceptedAnswers: ["ni"], kana: "に", romaji: "ni" },
	{ acceptedAnswers: ["nu"], kana: "ぬ", romaji: "nu" },
	{ acceptedAnswers: ["ne"], kana: "ね", romaji: "ne" },
	{ acceptedAnswers: ["no"], kana: "の", romaji: "no" },
	{ acceptedAnswers: ["ha"], kana: "は", romaji: "ha" },
	{ acceptedAnswers: ["hi"], kana: "ひ", romaji: "hi" },
	{ acceptedAnswers: ["fu"], kana: "ふ", romaji: "fu" },
	{ acceptedAnswers: ["he"], kana: "へ", romaji: "he" },
	{ acceptedAnswers: ["ho"], kana: "ほ", romaji: "ho" },
	{ acceptedAnswers: ["ma"], kana: "ま", romaji: "ma" },
	{ acceptedAnswers: ["mi"], kana: "み", romaji: "mi" },
	{ acceptedAnswers: ["mu"], kana: "む", romaji: "mu" },
	{ acceptedAnswers: ["me"], kana: "め", romaji: "me" },
	{ acceptedAnswers: ["mo"], kana: "も", romaji: "mo" },
	{ acceptedAnswers: ["ya"], kana: "や", romaji: "ya" },
	{ acceptedAnswers: ["yu"], kana: "ゆ", romaji: "yu" },
	{ acceptedAnswers: ["yo"], kana: "よ", romaji: "yo" },
	{ acceptedAnswers: ["ra"], kana: "ら", romaji: "ra" },
	{ acceptedAnswers: ["ri"], kana: "り", romaji: "ri" },
	{ acceptedAnswers: ["ru"], kana: "る", romaji: "ru" },
	{ acceptedAnswers: ["re"], kana: "れ", romaji: "re" },
	{ acceptedAnswers: ["ro"], kana: "ろ", romaji: "ro" },
	{ acceptedAnswers: ["wa"], kana: "わ", romaji: "wa" },
	{ acceptedAnswers: ["o", "wo"], kana: "を", romaji: "o" },
	{ acceptedAnswers: ["n"], kana: "ん", romaji: "n" },
	{ acceptedAnswers: ["ga"], kana: "が", romaji: "ga" },
	{ acceptedAnswers: ["gi"], kana: "ぎ", romaji: "gi" },
	{ acceptedAnswers: ["gu"], kana: "ぐ", romaji: "gu" },
	{ acceptedAnswers: ["ge"], kana: "げ", romaji: "ge" },
	{ acceptedAnswers: ["go"], kana: "ご", romaji: "go" },
	{ acceptedAnswers: ["za"], kana: "ざ", romaji: "za" },
	{ acceptedAnswers: ["ji"], kana: "じ", romaji: "ji" },
	{ acceptedAnswers: ["zu"], kana: "ず", romaji: "zu" },
	{ acceptedAnswers: ["ze"], kana: "ぜ", romaji: "ze" },
	{ acceptedAnswers: ["zo"], kana: "ぞ", romaji: "zo" },
	{ acceptedAnswers: ["da"], kana: "だ", romaji: "da" },
	{ acceptedAnswers: ["ji"], kana: "ぢ", romaji: "ji" },
	{ acceptedAnswers: ["zu"], kana: "づ", romaji: "zu" },
	{ acceptedAnswers: ["de"], kana: "で", romaji: "de" },
	{ acceptedAnswers: ["do"], kana: "ど", romaji: "do" },
	{ acceptedAnswers: ["ba"], kana: "ば", romaji: "ba" },
	{ acceptedAnswers: ["bi"], kana: "び", romaji: "bi" },
	{ acceptedAnswers: ["bu"], kana: "ぶ", romaji: "bu" },
	{ acceptedAnswers: ["be"], kana: "べ", romaji: "be" },
	{ acceptedAnswers: ["bo"], kana: "ぼ", romaji: "bo" },
	{ acceptedAnswers: ["pa"], kana: "ぱ", romaji: "pa" },
	{ acceptedAnswers: ["pi"], kana: "ぴ", romaji: "pi" },
	{ acceptedAnswers: ["pu"], kana: "ぷ", romaji: "pu" },
	{ acceptedAnswers: ["pe"], kana: "ぺ", romaji: "pe" },
	{ acceptedAnswers: ["po"], kana: "ぽ", romaji: "po" },
	{ acceptedAnswers: ["kya"], kana: "きゃ", romaji: "kya" },
	{ acceptedAnswers: ["kyu"], kana: "きゅ", romaji: "kyu" },
	{ acceptedAnswers: ["kyo"], kana: "きょ", romaji: "kyo" },
	{ acceptedAnswers: ["sha"], kana: "しゃ", romaji: "sha" },
	{ acceptedAnswers: ["shu"], kana: "しゅ", romaji: "shu" },
	{ acceptedAnswers: ["sho"], kana: "しょ", romaji: "sho" },
	{ acceptedAnswers: ["cha", "tya"], kana: "ちゃ", romaji: "cha" },
	{ acceptedAnswers: ["chu", "tyu"], kana: "ちゅ", romaji: "chu" },
	{ acceptedAnswers: ["cho", "tyo"], kana: "ちょ", romaji: "cho" },
	{ acceptedAnswers: ["nya"], kana: "にゃ", romaji: "nya" },
	{ acceptedAnswers: ["nyu"], kana: "にゅ", romaji: "nyu" },
	{ acceptedAnswers: ["nyo"], kana: "にょ", romaji: "nyo" },
	{ acceptedAnswers: ["hya"], kana: "ひゃ", romaji: "hya" },
	{ acceptedAnswers: ["hyu"], kana: "ひゅ", romaji: "hyu" },
	{ acceptedAnswers: ["hyo"], kana: "ひょ", romaji: "hyo" },
	{ acceptedAnswers: ["mya"], kana: "みゃ", romaji: "mya" },
	{ acceptedAnswers: ["myu"], kana: "みゅ", romaji: "myu" },
	{ acceptedAnswers: ["myo"], kana: "みょ", romaji: "myo" },
	{ acceptedAnswers: ["rya"], kana: "りゃ", romaji: "rya" },
	{ acceptedAnswers: ["ryu"], kana: "りゅ", romaji: "ryu" },
	{ acceptedAnswers: ["ryo"], kana: "りょ", romaji: "ryo" },
	{ acceptedAnswers: ["gya"], kana: "ぎゃ", romaji: "gya" },
	{ acceptedAnswers: ["gyu"], kana: "ぎゅ", romaji: "gyu" },
	{ acceptedAnswers: ["gyo"], kana: "ぎょ", romaji: "gyo" },
	{ acceptedAnswers: ["ja", "jya"], kana: "じゃ", romaji: "ja" },
	{ acceptedAnswers: ["ju", "jyu"], kana: "じゅ", romaji: "ju" },
	{ acceptedAnswers: ["jo", "jyo"], kana: "じょ", romaji: "jo" },
	{ acceptedAnswers: ["bya"], kana: "びゃ", romaji: "bya" },
	{ acceptedAnswers: ["byu"], kana: "びゅ", romaji: "byu" },
	{ acceptedAnswers: ["byo"], kana: "びょ", romaji: "byo" },
	{ acceptedAnswers: ["pya"], kana: "ぴゃ", romaji: "pya" },
	{ acceptedAnswers: ["pyu"], kana: "ぴゅ", romaji: "pyu" },
	{ acceptedAnswers: ["pyo"], kana: "ぴょ", romaji: "pyo" },
] as const satisfies Character[];

export const katakana = [
	{ acceptedAnswers: ["a"], kana: "ア", romaji: "a" },
	{ acceptedAnswers: ["i"], kana: "イ", romaji: "i" },
	{ acceptedAnswers: ["u"], kana: "ウ", romaji: "u" },
	{ acceptedAnswers: ["e"], kana: "エ", romaji: "e" },
	{ acceptedAnswers: ["o"], kana: "オ", romaji: "o" },
	{ acceptedAnswers: ["ka"], kana: "カ", romaji: "ka" },
	{ acceptedAnswers: ["ki"], kana: "キ", romaji: "ki" },
	{ acceptedAnswers: ["ku"], kana: "ク", romaji: "ku" },
	{ acceptedAnswers: ["ke"], kana: "ケ", romaji: "ke" },
	{ acceptedAnswers: ["ko"], kana: "コ", romaji: "ko" },
	{ acceptedAnswers: ["sa"], kana: "サ", romaji: "sa" },
	{ acceptedAnswers: ["shi"], kana: "シ", romaji: "shi" },
	{ acceptedAnswers: ["su"], kana: "ス", romaji: "su" },
	{ acceptedAnswers: ["se"], kana: "セ", romaji: "se" },
	{ acceptedAnswers: ["so"], kana: "ソ", romaji: "so" },
	{ acceptedAnswers: ["ta"], kana: "タ", romaji: "ta" },
	{ acceptedAnswers: ["chi"], kana: "チ", romaji: "chi" },
	{ acceptedAnswers: ["tsu"], kana: "ツ", romaji: "tsu" },
	{ acceptedAnswers: ["te"], kana: "テ", romaji: "te" },
	{ acceptedAnswers: ["to"], kana: "ト", romaji: "to" },
	{ acceptedAnswers: ["na"], kana: "ナ", romaji: "na" },
	{ acceptedAnswers: ["ni"], kana: "ニ", romaji: "ni" },
	{ acceptedAnswers: ["nu"], kana: "ヌ", romaji: "nu" },
	{ acceptedAnswers: ["ne"], kana: "ネ", romaji: "ne" },
	{ acceptedAnswers: ["no"], kana: "ノ", romaji: "no" },
	{ acceptedAnswers: ["ha"], kana: "ハ", romaji: "ha" },
	{ acceptedAnswers: ["hi"], kana: "ヒ", romaji: "hi" },
	{ acceptedAnswers: ["fu"], kana: "フ", romaji: "fu" },
	{ acceptedAnswers: ["he"], kana: "ヘ", romaji: "he" },
	{ acceptedAnswers: ["ho"], kana: "ホ", romaji: "ho" },
	{ acceptedAnswers: ["ma"], kana: "マ", romaji: "ma" },
	{ acceptedAnswers: ["mi"], kana: "ミ", romaji: "mi" },
	{ acceptedAnswers: ["mu"], kana: "ム", romaji: "mu" },
	{ acceptedAnswers: ["me"], kana: "メ", romaji: "me" },
	{ acceptedAnswers: ["mo"], kana: "モ", romaji: "mo" },
	{ acceptedAnswers: ["ya"], kana: "ヤ", romaji: "ya" },
	{ acceptedAnswers: ["yu"], kana: "ユ", romaji: "yu" },
	{ acceptedAnswers: ["yo"], kana: "ヨ", romaji: "yo" },
	{ acceptedAnswers: ["ra"], kana: "ラ", romaji: "ra" },
	{ acceptedAnswers: ["ri"], kana: "リ", romaji: "ri" },
	{ acceptedAnswers: ["ru"], kana: "ル", romaji: "ru" },
	{ acceptedAnswers: ["re"], kana: "レ", romaji: "re" },
	{ acceptedAnswers: ["ro"], kana: "ロ", romaji: "ro" },
	{ acceptedAnswers: ["wa"], kana: "ワ", romaji: "wa" },
	{ acceptedAnswers: ["o", "wo"], kana: "ヲ", romaji: "o" },
	{ acceptedAnswers: ["n"], kana: "ン", romaji: "n" },
	{ acceptedAnswers: ["ga"], kana: "ガ", romaji: "ga" },
	{ acceptedAnswers: ["gi"], kana: "ギ", romaji: "gi" },
	{ acceptedAnswers: ["gu"], kana: "グ", romaji: "gu" },
	{ acceptedAnswers: ["ge"], kana: "ゲ", romaji: "ge" },
	{ acceptedAnswers: ["go"], kana: "ゴ", romaji: "go" },
	{ acceptedAnswers: ["za"], kana: "ザ", romaji: "za" },
	{ acceptedAnswers: ["ji"], kana: "ジ", romaji: "ji" },
	{ acceptedAnswers: ["zu"], kana: "ズ", romaji: "zu" },
	{ acceptedAnswers: ["ze"], kana: "ゼ", romaji: "ze" },
	{ acceptedAnswers: ["zo"], kana: "ゾ", romaji: "zo" },
	{ acceptedAnswers: ["da"], kana: "ダ", romaji: "da" },
	{ acceptedAnswers: ["ji"], kana: "ヂ", romaji: "ji" },
	{ acceptedAnswers: ["zu"], kana: "ヅ", romaji: "zu" },
	{ acceptedAnswers: ["de"], kana: "デ", romaji: "de" },
	{ acceptedAnswers: ["do"], kana: "ド", romaji: "do" },
	{ acceptedAnswers: ["ba"], kana: "バ", romaji: "ba" },
	{ acceptedAnswers: ["bi"], kana: "ビ", romaji: "bi" },
	{ acceptedAnswers: ["bu"], kana: "ブ", romaji: "bu" },
	{ acceptedAnswers: ["be"], kana: "ベ", romaji: "be" },
	{ acceptedAnswers: ["bo"], kana: "ボ", romaji: "bo" },
	{ acceptedAnswers: ["pa"], kana: "パ", romaji: "pa" },
	{ acceptedAnswers: ["pi"], kana: "ピ", romaji: "pi" },
	{ acceptedAnswers: ["pu"], kana: "プ", romaji: "pu" },
	{ acceptedAnswers: ["pe"], kana: "ペ", romaji: "pe" },
	{ acceptedAnswers: ["po"], kana: "ポ", romaji: "po" },
	{ acceptedAnswers: ["kya"], kana: "キャ", romaji: "kya" },
	{ acceptedAnswers: ["kyu"], kana: "キュ", romaji: "kyu" },
	{ acceptedAnswers: ["kyo"], kana: "キョ", romaji: "kyo" },
	{ acceptedAnswers: ["sha"], kana: "シャ", romaji: "sha" },
	{ acceptedAnswers: ["shu"], kana: "シュ", romaji: "shu" },
	{ acceptedAnswers: ["sho"], kana: "ショ", romaji: "sho" },
	{ acceptedAnswers: ["cha"], kana: "チャ", romaji: "cha" },
	{ acceptedAnswers: ["chu"], kana: "チュ", romaji: "chu" },
	{ acceptedAnswers: ["cho"], kana: "チョ", romaji: "cho" },
	{ acceptedAnswers: ["nya"], kana: "ニャ", romaji: "nya" },
	{ acceptedAnswers: ["nyu"], kana: "ニュ", romaji: "nyu" },
	{ acceptedAnswers: ["nyo"], kana: "ニョ", romaji: "nyo" },
	{ acceptedAnswers: ["hya"], kana: "ヒャ", romaji: "hya" },
	{ acceptedAnswers: ["hyu"], kana: "ヒュ", romaji: "hyu" },
	{ acceptedAnswers: ["hyo"], kana: "ヒョ", romaji: "hyo" },
	{ acceptedAnswers: ["mya"], kana: "ミャ", romaji: "mya" },
	{ acceptedAnswers: ["myu"], kana: "ミュ", romaji: "myu" },
	{ acceptedAnswers: ["myo"], kana: "ミョ", romaji: "myo" },
	{ acceptedAnswers: ["rya"], kana: "リャ", romaji: "rya" },
	{ acceptedAnswers: ["ryu"], kana: "リュ", romaji: "ryu" },
	{ acceptedAnswers: ["ryo"], kana: "リョ", romaji: "ryo" },
	{ acceptedAnswers: ["gya"], kana: "ギャ", romaji: "gya" },
	{ acceptedAnswers: ["gyu"], kana: "ギュ", romaji: "gyu" },
	{ acceptedAnswers: ["gyo"], kana: "ギョ", romaji: "gyo" },
	{ acceptedAnswers: ["ja"], kana: "ジャ", romaji: "ja" },
	{ acceptedAnswers: ["ju"], kana: "ジュ", romaji: "ju" },
	{ acceptedAnswers: ["jo"], kana: "ジョ", romaji: "jo" },
	{ acceptedAnswers: ["bya"], kana: "ビャ", romaji: "bya" },
	{ acceptedAnswers: ["byu"], kana: "ビュ", romaji: "byu" },
	{ acceptedAnswers: ["byo"], kana: "ビョ", romaji: "byo" },
	{ acceptedAnswers: ["pya"], kana: "ピャ", romaji: "pya" },
	{ acceptedAnswers: ["pyu"], kana: "ピュ", romaji: "pyu" },
	{ acceptedAnswers: ["pyo"], kana: "ピョ", romaji: "pyo" },
] as const satisfies Character[];

export const allCharacters = [...hiragana, ...katakana];
export const allCharactersKV = indexBy(allCharacters, ({ kana }) => kana);
