export type KanaType =
  | "hiragana"
  | "hiragana-combos"
  | "katakana"
  | "katakana-combos";

export type Character = {
  column: number;
  isSelected: boolean;
  kana: string;
  romaji: string;
  row: number;
  type: KanaType;
  weight: number; // defaults to 0
};

export const kanas: Character[] = [
  {
    column: 0,
    isSelected: false,
    kana: "あ",
    romaji: "a",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "い",
    romaji: "i",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "う",
    romaji: "u",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "え",
    romaji: "e",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "お",
    romaji: "o",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "か",
    romaji: "ka",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "き",
    romaji: "ki",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "く",
    romaji: "ku",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "け",
    romaji: "ke",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "こ",
    romaji: "ko",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "さ",
    romaji: "sa",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "し",
    romaji: "shi",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "す",
    romaji: "su",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "せ",
    romaji: "se",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "そ",
    romaji: "so",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "た",
    romaji: "ta",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "ち",
    romaji: "chi",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "つ",
    romaji: "tsu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "て",
    romaji: "te",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "と",
    romaji: "to",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "な",
    romaji: "na",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "に",
    romaji: "ni",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ぬ",
    romaji: "nu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ね",
    romaji: "ne",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "の",
    romaji: "no",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "は",
    romaji: "ha",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ひ",
    romaji: "hi",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ふ",
    romaji: "fu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "へ",
    romaji: "he",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ほ",
    romaji: "ho",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "ま",
    romaji: "ma",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "み",
    romaji: "mi",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "む",
    romaji: "mu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "め",
    romaji: "me",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "も",
    romaji: "mo",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "や",
    romaji: "ya",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ゆ",
    romaji: "yu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "よ",
    romaji: "yo",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "ら",
    romaji: "ra",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "り",
    romaji: "ri",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "る",
    romaji: "ru",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "れ",
    romaji: "re",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "ろ",
    romaji: "ro",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "わ",
    romaji: "wa",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "を",
    romaji: "wo",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 10,
    isSelected: false,
    kana: "ん",
    romaji: "n",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "が",
    romaji: "ga",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ぎ",
    romaji: "gi",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ぐ",
    romaji: "gu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "げ",
    romaji: "ge",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ご",
    romaji: "go",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ざ",
    romaji: "za",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "じ",
    romaji: "ji",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ず",
    romaji: "zu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ぜ",
    romaji: "ze",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ぞ",
    romaji: "zo",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "だ",
    romaji: "da",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "ぢ",
    romaji: "ji",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "づ",
    romaji: "zu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "で",
    romaji: "de",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "ど",
    romaji: "do",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "ば",
    romaji: "ba",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "び",
    romaji: "bi",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "ぶ",
    romaji: "bu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "べ",
    romaji: "be",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "ぼ",
    romaji: "bo",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "ぱ",
    romaji: "pa",
    row: 0,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "ぴ",
    romaji: "pi",
    row: 1,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "ぷ",
    romaji: "pu",
    row: 2,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "ぺ",
    romaji: "pe",
    row: 3,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "ぽ",
    romaji: "po",
    row: 4,
    type: "hiragana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "きゃ",
    romaji: "kya",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "きゅ",
    romaji: "kyu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "きょ",
    romaji: "kyo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "しゃ",
    romaji: "sha",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "しゅ",
    romaji: "shu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "しょ",
    romaji: "sho",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "ちゃ",
    romaji: "cha",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "ちゅ",
    romaji: "chu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "ちょ",
    romaji: "cho",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "にゃ",
    romaji: "nya",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "にゅ",
    romaji: "nyu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "にょ",
    romaji: "nyo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ひゃ",
    romaji: "hya",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ひゅ",
    romaji: "hyu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ひょ",
    romaji: "hyo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "みゃ",
    romaji: "mya",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "みゅ",
    romaji: "myu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "みょ",
    romaji: "myo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "りゃ",
    romaji: "rya",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "りゅ",
    romaji: "ryu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "りょ",
    romaji: "ryo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ぎゃ",
    romaji: "gya",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ぎゅ",
    romaji: "gyu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ぎょ",
    romaji: "gyo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "じゃ",
    romaji: "ja",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "じゅ",
    romaji: "ju",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "じょ",
    romaji: "jo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "ぢゃ",
    romaji: "ja",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "ぢゅ",
    romaji: "ju",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "ぢょ",
    romaji: "jo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 10,
    isSelected: false,
    kana: "びゃ",
    romaji: "bya",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 10,
    isSelected: false,
    kana: "びゅ",
    romaji: "byu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 10,
    isSelected: false,
    kana: "びょ",
    romaji: "byo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ぴゃ",
    romaji: "pya",
    row: 0,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ぴゅ",
    romaji: "pyu",
    row: 1,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ぴょ",
    romaji: "pyo",
    row: 2,
    type: "hiragana-combos",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "ア",
    romaji: "a",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "イ",
    romaji: "i",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "ウ",
    romaji: "u",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "エ",
    romaji: "e",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "オ",
    romaji: "o",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "カ",
    romaji: "ka",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "キ",
    romaji: "ki",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "ク",
    romaji: "ku",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "ケ",
    romaji: "ke",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "コ",
    romaji: "ko",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "サ",
    romaji: "sa",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "シ",
    romaji: "shi",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "ス",
    romaji: "su",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "セ",
    romaji: "se",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "ソ",
    romaji: "so",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "タ",
    romaji: "ta",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "チ",
    romaji: "chi",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "ツ",
    romaji: "tsu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "テ",
    romaji: "te",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "ト",
    romaji: "to",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ナ",
    romaji: "na",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ニ",
    romaji: "ni",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ヌ",
    romaji: "nu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ネ",
    romaji: "ne",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ノ",
    romaji: "no",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ハ",
    romaji: "ha",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ヒ",
    romaji: "hi",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "フ",
    romaji: "fu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ヘ",
    romaji: "he",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ホ",
    romaji: "ho",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "マ",
    romaji: "ma",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "ミ",
    romaji: "mi",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "ム",
    romaji: "mu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "メ",
    romaji: "me",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "モ",
    romaji: "mo",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ヤ",
    romaji: "ya",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ユ",
    romaji: "yu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ヨ",
    romaji: "yo",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "ラ",
    romaji: "ra",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "リ",
    romaji: "ri",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "ル",
    romaji: "ru",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "レ",
    romaji: "re",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "ロ",
    romaji: "ro",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "ワ",
    romaji: "wa",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "ヲ",
    romaji: "wo",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 10,
    isSelected: false,
    kana: "ン",
    romaji: "n",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ガ",
    romaji: "ga",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ギ",
    romaji: "gi",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "グ",
    romaji: "gu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ゲ",
    romaji: "ge",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ゴ",
    romaji: "go",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ザ",
    romaji: "za",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ジ",
    romaji: "ji",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ズ",
    romaji: "zu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ゼ",
    romaji: "ze",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 12,
    isSelected: false,
    kana: "ゾ",
    romaji: "zo",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "ダ",
    romaji: "da",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "ヂ",
    romaji: "ji",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "ヅ",
    romaji: "zu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "デ",
    romaji: "de",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 13,
    isSelected: false,
    kana: "ド",
    romaji: "do",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "バ",
    romaji: "ba",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "ビ",
    romaji: "bi",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "ブ",
    romaji: "bu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "ベ",
    romaji: "be",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 14,
    isSelected: false,
    kana: "ボ",
    romaji: "bo",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "パ",
    romaji: "pa",
    row: 0,
    type: "katakana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "ピ",
    romaji: "pi",
    row: 1,
    type: "katakana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "プ",
    romaji: "pu",
    row: 2,
    type: "katakana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "ペ",
    romaji: "pe",
    row: 3,
    type: "katakana",
    weight: 0,
  },
  {
    column: 15,
    isSelected: false,
    kana: "ポ",
    romaji: "po",
    row: 4,
    type: "katakana",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "キャ",
    romaji: "kya",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "キュ",
    romaji: "kyu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 0,
    isSelected: false,
    kana: "キョ",
    romaji: "kyo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "シャ",
    romaji: "sha",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "シュ",
    romaji: "shu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 1,
    isSelected: false,
    kana: "ショ",
    romaji: "sho",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "チャ",
    romaji: "cha",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "チュ",
    romaji: "chu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 2,
    isSelected: false,
    kana: "チョ",
    romaji: "cho",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "ニャ",
    romaji: "nya",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "ニュ",
    romaji: "nyu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 3,
    isSelected: false,
    kana: "ニョ",
    romaji: "nyo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ヒャ",
    romaji: "hya",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ヒュ",
    romaji: "hyu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 4,
    isSelected: false,
    kana: "ヒョ",
    romaji: "hyo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ミャ",
    romaji: "mya",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ミュ",
    romaji: "myu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 5,
    isSelected: false,
    kana: "ミョ",
    romaji: "myo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "リャ",
    romaji: "rya",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "リュ",
    romaji: "ryu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 6,
    isSelected: false,
    kana: "リョ",
    romaji: "ryo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ギャ",
    romaji: "gya",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ギュ",
    romaji: "gyu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 7,
    isSelected: false,
    kana: "ギョ",
    romaji: "gyo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "ジャ",
    romaji: "ja",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "ジュ",
    romaji: "ju",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 8,
    isSelected: false,
    kana: "ジョ",
    romaji: "jo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "ヂャ",
    romaji: "ja",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "ヂュ",
    romaji: "ju",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 9,
    isSelected: false,
    kana: "ヂョ",
    romaji: "jo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 10,
    isSelected: false,
    kana: "ビャ",
    romaji: "bya",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 10,
    isSelected: false,
    kana: "ビュ",
    romaji: "byu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 10,
    isSelected: false,
    kana: "ビョ",
    romaji: "byo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ピャ",
    romaji: "pya",
    row: 0,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ピュ",
    romaji: "pyu",
    row: 1,
    type: "katakana-combos",
    weight: 0,
  },
  {
    column: 11,
    isSelected: false,
    kana: "ピョ",
    romaji: "pyo",
    row: 2,
    type: "katakana-combos",
    weight: 0,
  },
];
