import type { Character, hiragana, katakana } from "./characters";

export type Stage<T extends Character[]> = Readonly<{
	id: string;
	kanas: T[number]["kana"][];
}>;

export const hiraganaStages: Stage<typeof hiragana>[] = [
	{ id: "vowels", kanas: ["あ", "い", "う", "え", "お"] },
	{ id: "k-group", kanas: ["か", "き", "く", "け", "こ"] },
	{ id: "s-group", kanas: ["さ", "し", "す", "せ", "そ"] },
	{ id: "t-group", kanas: ["た", "ち", "つ", "て", "と"] },
	{ id: "n-group", kanas: ["な", "に", "ぬ", "ね", "の"] },
	{ id: "h-group", kanas: ["は", "ひ", "ふ", "へ", "ほ"] },
	{ id: "m-group", kanas: ["ま", "み", "む", "め", "も"] },
	{ id: "y-group", kanas: ["や", "ゆ", "よ"] },
	{ id: "r-group", kanas: ["ら", "り", "る", "れ", "ろ"] },
	{ id: "w-group", kanas: ["わ", "を"] },
	{ id: "n", kanas: ["ん"] },
	{ id: "g-group", kanas: ["が", "ぎ", "ぐ", "げ", "ご"] },
	{ id: "z-group", kanas: ["ざ", "じ", "ず", "ぜ", "ぞ"] },
	{ id: "d-group", kanas: ["だ", "ぢ", "づ", "で", "ど"] },
	{ id: "b-group", kanas: ["ば", "び", "ぶ", "べ", "ぼ"] },
	{ id: "p-group", kanas: ["ぱ", "ぴ", "ぷ", "ぺ", "ぽ"] },
	{
		id: "combos",
		kanas: [
			"きゃ",
			"きゅ",
			"きょ",
			"しゃ",
			"しゅ",
			"しょ",
			"ちゃ",
			"ちゅ",
			"ちょ",
			"にゃ",
			"にゅ",
			"にょ",
			"ひゃ",
			"ひゅ",
			"ひょ",
			"みゃ",
			"みゅ",
			"みょ",
			"りゃ",
			"りゅ",
			"りょ",
			"ぎゃ",
			"ぎゅ",
			"ぎょ",
			"じゃ",
			"じゅ",
			"じょ",
			"びゃ",
			"びゅ",
			"びょ",
			"ぴゃ",
			"ぴゅ",
			"ぴょ",
		],
	},
] as const;

export const katakanaStages: Stage<typeof katakana>[] = [
	{ id: "vowels", kanas: ["ア", "イ", "ウ", "エ", "オ"] },
	{ id: "k-group", kanas: ["カ", "キ", "ク", "ケ", "コ"] },
	{ id: "s-group", kanas: ["サ", "シ", "ス", "セ", "ソ"] },
	{ id: "t-group", kanas: ["タ", "チ", "ツ", "テ", "ト"] },
	{ id: "n-group", kanas: ["ナ", "ニ", "ヌ", "ネ", "ノ"] },
	{ id: "h-group", kanas: ["ハ", "ヒ", "フ", "ヘ", "ホ"] },
	{ id: "m-group", kanas: ["マ", "ミ", "ム", "メ", "モ"] },
	{ id: "y-group", kanas: ["ヤ", "ユ", "ヨ"] },
	{ id: "r-group", kanas: ["ラ", "リ", "ル", "レ", "ロ"] },
	{ id: "w-group", kanas: ["ワ", "ヲ"] },
	{ id: "n", kanas: ["ン"] },
	{ id: "g-group", kanas: ["ガ", "ギ", "グ", "ゲ", "ゴ"] },
	{ id: "z-group", kanas: ["ザ", "ジ", "ズ", "ゼ", "ゾ"] },
	{ id: "d-group", kanas: ["ダ", "ヂ", "ヅ", "デ", "ド"] },
	{ id: "b-group", kanas: ["バ", "ビ", "ブ", "ベ", "ボ"] },
	{ id: "p-group", kanas: ["パ", "ピ", "プ", "ペ", "ポ"] },
	{
		id: "combos",
		kanas: [
			"キャ",
			"キュ",
			"キョ",
			"シャ",
			"シュ",
			"ショ",
			"チャ",
			"チュ",
			"チョ",
			"ニャ",
			"ニュ",
			"ニョ",
			"ヒャ",
			"ヒュ",
			"ヒョ",
			"ミャ",
			"ミュ",
			"ミョ",
			"リャ",
			"リュ",
			"リョ",
			"ギャ",
			"ギュ",
			"ギョ",
			"ジャ",
			"ジュ",
			"ジョ",
			"ビャ",
			"ビュ",
			"ビョ",
			"ピャ",
			"ピュ",
			"ピョ",
		],
	},
] as const;
